# Layer identification
BBPATH .= ":${LAYERDIR}"

# Recipe paths
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

# Layer name
BBFILE_COLLECTIONS += "systemmonitor"

# Recipe pattern match
BBFILE_PATTERN_systemmonitor = "^${LAYERDIR}/"

# Layer priority
BBFILE_PRIORITY_systemmonitor = "8"

# Layer compatibility
LAYERDEPENDS_systemmonitor = "core meta-qt6"
LAYERSERIES_COMPAT_systemmonitor = "kirkstone"
